name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-03-12"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = ""
# 配置 entry-point
entry-point = "src/main.tsx"  # 这里设置为您的入口文件
