name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-03-12"

[[kv_namespaces]]
kv_namespaces = [
  { binding = "TODO", id = "8b64f36f20f343faaf39108caf37c708" }
]
