name = "worker"  # 修改为"worker"

pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-03-12"

[[kv_namespaces]]  # 配置 KV 存储
kv_namespaces = [
  { binding = "TODO", id = "06779da69404b431db6e566b4846d64db", preview_id = "06779da69404b431db6e566b4846d64db" }
]


