name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-03-12"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "8b64f36f20f343faaf39108caf37c708"
